apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ops
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: chat-ops
          image: ghcr.io/reiaxu/chat-ops:v1.4.0
      imagePullSecrets:
        - name: github-container-registry
