apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ops
  namespace: default
spec:
  selector:
    matchLabels:
      app: chat-ops
  template:
    metadata:
      labels:
        app: chat-ops
    spec:
      containers:
        - name: chat-ops
          image: ghcr.io/reiaxu/chat-ops:v1.3.3
      imagePullSecrets:
        - name: github-container-registry
