name: Create release with version number

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Type of release
        # Input has to be provided for the workflow to run
        required: true
        options:
        # increment first version number
        - major
        # increment second version number
        - minor
        # increment third version number
        - patch
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  get-version:
    name: Find current version number
    runs-on: ubuntu-latest
    # Mapping outputs of first, second and third version numbers
    outputs:
      tag1: ${{ steps.describe1.outputs.tag }}
      tag2: ${{ steps.describe2.outputs.tag }}
      tag3: ${{ steps.describe3.outputs.tag }}
    steps:
      - run: echo "Current version number is $(git describe --tags)"
      - id: describe1
        run: echo "tag=$(git describe --tags 2> /dev/null | grep -o -E '[0-9]+' | sed -n '1p' || echo -n "0")" >> $GITHUB_OUTPUT
      - id: describe2
        run: echo "tag=$(git describe --tags 2> /dev/null | grep -o -E '[0-9]+' | sed -n '2p' || echo -n "0")" >> $GITHUB_OUTPUT
      - id: describe3
        run: echo "tag=$(git describe --tags 2> /dev/null | grep -o -E '[0-9]+' | sed -n '3p' || echo -n "0")" >> $GITHUB_OUTPUT          
  major-version:
    name: Modify first version number
    if: ${{ github.event.inputs.message == 'major' }}
    runs-on: ubuntu-latest
    needs: get-version
    outputs:
      major-tag: ${{ steps.major.outputs.tag }}
    steps:
      - run: echo "Update major release"
      - id: major
        run: |
          inc=${{ needs.get-version.outputs.tag1 }}
          inc=$((++inc))
          echo "tag=format('v{0}.{1}.{2}', inc, '0', '0')" >> $GITHUB_OUTPUT
          gh release create "$tag"
  minor-version:
    name: Modify second version number
    if: ${{ github.event.inputs.message == 'minor' }}
    runs-on: ubuntu-latest
    needs: get-version
    outputs:
      minor-tag: ${{ steps.minor.outputs.tag }}
    steps:
      - run: echo "Update minor release"
      - id: minor
        run: |
          inc=${{ needs.get-version.outputs.tag2 }}
          inc=$((++inc))
          echo "tag=format('v{0}.{1}.{2}', ${{ needs.get-version.outputs.tag1 }}, inc, '0')" >> $GITHUB_OUTPUT
          gh release create "$tag"
  patch-version:
    name: Modify third version number
    if: ${{ github.event.inputs.message == 'patch' }}
    runs-on: ubuntu-latest
    needs: get-version
    outputs:
      patch-tag: ${{ steps.patch.outputs.tag }}
    steps:
      - run: echo "Update patch release"
      - id: patch
        run: |
          inc=${{ needs.get-version.outputs.tag3 }}
          inc=$((++inc))
          echo "tag=format('v{0}.{1}.{2}', ${{ needs.get-version.outputs.tag1 }}, ${{ needs.get-version.outputs.tag2 }}, inc)" >> $GITHUB_OUTPUT
          gh release create "$tag"
